# Generated by Django 4.0.1 on 2022-01-31 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import puzzles.models


class Migration(migrations.Migration):

    replaces = [('puzzles', '0001_initial'), ('puzzles', '0002_location_userzulipstatus_userprofile_uploadedfile_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('text', models.CharField(max_length=200)),
                ('css_name', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'priorities',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('text', models.CharField(max_length=200)),
                ('css_name', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'statuses',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('tags', models.ManyToManyField(to='puzzles.Tag')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('spreadsheet', models.URLField(blank=True)),
                ('answer', models.CharField(blank=True, max_length=200)),
                ('checkAnswerLink', models.URLField(blank=True)),
                ('priority', models.ForeignKey(default=puzzles.models.defaultPriority, on_delete=django.db.models.deletion.CASCADE, to='puzzles.priority')),
                ('solvers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=puzzles.models.defaultStatus, on_delete=django.db.models.deletion.CASCADE, to='puzzles.status')),
                ('tags', models.ManyToManyField(default=puzzles.models.defaultTags, to='puzzles.Tag')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_phone', models.CharField(blank=True, help_text='Phone number on which answer callbacks from Hunt HQ will be received.\nIf empty, users will have to enter their own phone number when submitting an answer.', max_length=255)),
                ('motd', models.TextField(blank=True)),
                ('default_priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.priority')),
                ('default_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.status')),
                ('default_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.tag')),
                ('default_taglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.taglist')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserZulipStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('none', 'Not created yet'), ('success', 'Zulip user successfully created'), ('failure', 'Zulip user could not be created')], default='none', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('backsolved', models.BooleanField()),
                ('phone', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('response', models.TextField(default='')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_name', models.CharField(max_length=200)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.tag')),
            ],
        ),
        migrations.CreateModel(
            name='QueuedAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle')),
            ],
            options={
                'unique_together': {('puzzle', 'answer')},
            },
        ),
        migrations.CreateModel(
            name='PuzzleWrongAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle')),
            ],
            options={
                'unique_together': {('puzzle', 'answer')},
            },
        ),
    ]
