# Generated by Django 4.1.5 on 2024-01-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_accesslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='stamp',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='intStamp',
            field=models.IntegerField(default=0),
        ),
    ]
