# Generated by Django 4.1.5 on 2024-01-07 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0005_jitsirooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jitsirooms',
            name='puzzle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle'),
        ),
    ]
