# Generated by Django 4.1.5 on 2024-01-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0006_alter_jitsirooms_puzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='jitsirooms',
            name='string_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
