# Generated by Django 5.1.4 on 2024-12-27 00:19

import django.db.models.deletion
import puzzles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('puzzles', '0008_config_puzzle_folder_config_puzzle_template'), ('puzzles', '0009_remove_config_puzzle_folder_and_more'), ('puzzles', '0010_puzzlefolder'), ('puzzles', '0011_alter_puzzlefolder_fid_alter_puzzlefolder_name'), ('puzzles', '0012_puzzletemplate'), ('puzzles', '0013_puzzlefolder_shareall_puzzlefolder_shareonly'), ('puzzles', '0014_remove_puzzlefolder_shareall_config_default_folder_and_more'), ('puzzles', '0015_puzzle_folder_puzzle_template'), ('puzzles', '0016_alter_config_default_folder_and_more'), ('puzzles', '0017_alter_puzzle_folder_alter_puzzle_template_and_more')]

    dependencies = [
        ('puzzles', '0007_jitsirooms_string_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('fid', models.CharField(blank=True, max_length=200)),
                ('shareOnly', models.ForeignKey(blank=True, help_text='User to share this folder with.  Leave null (default) to share with all users', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PuzzleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('fid', models.CharField(blank=True, max_length=200)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzlefolder')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='config',
            name='default_folder',
            field=models.ForeignKey(blank=True, help_text='Default Folder to use to share new puzzles.  Leave null to share by making world-editable instead', null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzlefolder'),
        ),
        migrations.AddField(
            model_name='config',
            name='default_template',
            field=models.ForeignKey(blank=True, help_text='Default spreadsheet to use to create new puzzles.  Leave null to create completely blank ones', null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzletemplate'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='folder',
            field=models.ForeignKey(blank=True, default=puzzles.models.defaultFolder, help_text='Google Drive folder to use to share this puzzle spreadsheet when first making it.  Leave null to share by making world-editable instead.', null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzlefolder'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='template',
            field=models.ForeignKey(blank=True, default=puzzles.models.defaultTemplate, help_text='Template to copy when first making this puzzle.  Leave null to create from scratch.', null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzletemplate'),
        ),
    ]
