# Generated by Django 5.1.4 on 2024-12-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_jitsirooms_string_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='puzzle_folder',
            field=models.CharField(blank=True, help_text='The folder ID (long hash string in the URL) of the shared folder where puzzles will be placed', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='puzzle_template',
            field=models.CharField(blank=True, help_text='The file ID (long hash string in the URL) of the spreadsheet to copy for new puzzles', max_length=255),
        ),
    ]
