# Generated by Django 5.1.4 on 2024-12-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0008_config_puzzle_folder_config_puzzle_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='puzzle_folder',
        ),
        migrations.RemoveField(
            model_name='config',
            name='puzzle_template',
        ),
    ]
