# Generated by Django 5.1.4 on 2024-12-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0009_remove_config_puzzle_folder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=200)),
                ('fid', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
