# Generated by Django 5.1.4 on 2024-12-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0010_puzzlefolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlefolder',
            name='fid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='puzzlefolder',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
