# Generated by Django 5.1.4 on 2024-12-26 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0011_alter_puzzlefolder_fid_alter_puzzlefolder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('fid', models.CharField(blank=True, max_length=200)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzlefolder')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
