# Generated by Django 5.1.4 on 2024-12-26 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0012_puzzletemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlefolder',
            name='shareAll',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='puzzlefolder',
            name='shareOnly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
