# Generated by Django 5.1.4 on 2024-12-26 22:38

import django.db.models.deletion
import puzzles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0014_remove_puzzlefolder_shareall_config_default_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='folder',
            field=models.ForeignKey(default=puzzles.models.defaultFolder, null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzlefolder'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='template',
            field=models.ForeignKey(default=puzzles.models.defaultTemplate, null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzletemplate'),
        ),
    ]
