# Generated by Django 5.1.4 on 2024-12-26 23:18

import django.db.models.deletion
import puzzles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0016_alter_config_default_folder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='folder',
            field=models.ForeignKey(blank=True, default=puzzles.models.defaultFolder, help_text='Google Drive folder to use to share this puzzle spreadsheet when first making it.  Leave null to share by making world-editable instead.', null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzlefolder'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='template',
            field=models.ForeignKey(blank=True, default=puzzles.models.defaultTemplate, help_text='Template to copy when first making this puzzle.  Leave null to create from scratch.', null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzletemplate'),
        ),
        migrations.AlterField(
            model_name='puzzlefolder',
            name='shareOnly',
            field=models.ForeignKey(blank=True, help_text='User to share this folder with.  Leave null (default) to share with all users', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
