# Generated by Django 5.1.4 on 2024-12-28 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0008_config_puzzle_folder_config_puzzle_template_squashed_0017_alter_puzzle_folder_alter_puzzle_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={},
        ),
        migrations.RenameField(
            model_name='accesslog',
            old_name='intStamp',
            new_name='accumulatedMinutes',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='order',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='linkedOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='puzzlefolder',
            name='shareOnly',
            field=models.ForeignKey(blank=True, help_text='User to share this folder with.  Leave null (default) to share with all users', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
