# Generated by Django 5.1.4 on 2024-12-28 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0008_config_puzzle_folder_config_puzzle_template_squashed_0017_alter_puzzle_folder_alter_puzzle_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_rounds', to='puzzles.round')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='puzzle',
            name='round',
            field=models.ForeignKey(blank=True, help_text='The round a given puzzle belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzles.round'),
        ),
    ]
