# Generated by Django 5.1.4 on 2024-12-28 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0018_alter_accesslog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 18, 14, 8, 820641)),
        ),
    ]
