# Generated by Django 5.1.4 on 2024-12-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0018_round_puzzle_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
