# Generated by Django 5.1.4 on 2024-12-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0019_alter_accesslog_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
