# Generated by Django 5.1.4 on 2024-12-29 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0018_alter_accesslog_options_and_more_squashed_0020_alter_accesslog_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 21, 49, 6, 293821, tzinfo=datetime.timezone.utc)),
        ),
    ]
