# Generated by Django 5.1.4 on 2024-12-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0018_round_puzzle_round'),
        ('puzzles', '0021_alter_accesslog_lastupdate'),
    ]

    operations = [
    ]
