# Generated by Django 5.1.4 on 2024-12-30 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0022_merge_20241230_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='lastUpdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
