# Generated by Django 5.1.4 on 2025-01-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0019_userprofile_picture'),
        ('puzzles', '0023_alter_accesslog_lastupdate'),
    ]

    operations = [
    ]
