# Generated by Django 5.1.4 on 2025-01-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0024_merge_20250101_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='description',
            field=models.CharField(blank=True, help_text='Short description of the given puzzle', max_length=280),
        ),
    ]
