# Generated by Django 5.1.4 on 2025-01-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0025_puzzle_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedHint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('urgent', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
