# Generated by Django 5.1.4 on 2025-01-06 01:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0027_queuedhint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedhint',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queuedhint',
            name='modifiedTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
