# Generated by Django 5.1.4 on 2025-01-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0028_queuedhint_createdtime_queuedhint_modifiedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='use_adc',
            field=models.BooleanField(default=False, help_text='Should puzzle Sheets be owned by a real user instead of a service account'),
        ),
    ]
