# Generated by Django 5.1.4 on 2025-01-12 15:30

import django.db.models.deletion
import puzzles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0029_config_use_adc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='default_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.tag'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='folder',
            field=models.ForeignKey(blank=True, default=puzzles.models.defaultFolder, help_text='Google Drive folder to use to share this puzzle spreadsheet when first making it.  Leave null to share by making world-editable instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzles.puzzlefolder'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='priority',
            field=models.ForeignKey(default=puzzles.models.defaultPriority, on_delete=django.db.models.deletion.SET_DEFAULT, to='puzzles.priority'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='status',
            field=models.ForeignKey(default=puzzles.models.defaultStatus, on_delete=django.db.models.deletion.SET_DEFAULT, to='puzzles.status'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='tags',
            field=models.ManyToManyField(blank=True, default=puzzles.models.defaultTags, to='puzzles.tag'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='template',
            field=models.ForeignKey(blank=True, default=puzzles.models.defaultTemplate, help_text='Template to copy when first making this puzzle.  Leave null to create from scratch.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzles.puzzletemplate'),
        ),
    ]
