# Generated by Django 5.1.4 on 2025-01-12 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0030_alter_config_default_tag_alter_puzzle_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='default_folder',
            field=models.ForeignKey(blank=True, help_text='Default Folder to use to share new puzzles.  Leave null to share by making world-editable instead', null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzles.puzzlefolder'),
        ),
        migrations.AlterField(
            model_name='config',
            name='default_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzles.tag'),
        ),
        migrations.AlterField(
            model_name='config',
            name='default_taglist',
            field=models.ForeignKey(help_text="This isn't actually used for anything (at the moment)", on_delete=django.db.models.deletion.CASCADE, to='puzzles.taglist'),
        ),
        migrations.AlterField(
            model_name='config',
            name='default_template',
            field=models.ForeignKey(blank=True, help_text='Default spreadsheet to use to create new puzzles.  Leave null to create completely blank ones', null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzles.puzzletemplate'),
        ),
        migrations.AlterField(
            model_name='puzzletemplate',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzles.puzzlefolder'),
        ),
        migrations.AlterField(
            model_name='round',
            name='parent_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_rounds', to='puzzles.round'),
        ),
    ]
