# Generated by Django 5.1.4 on 2025-01-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0031_alter_config_default_folder_alter_config_default_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedhint',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
