# Generated by Django 5.1.4 on 2026-01-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0033_puzzle_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='unloved_exempt_status',
            field=models.ManyToManyField(blank=True, related_name='exempt_status', to='puzzles.status'),
        ),
        migrations.AddField(
            model_name='config',
            name='unloved_exempt_tags',
            field=models.ManyToManyField(blank=True, related_name='exempt_tags', to='puzzles.tag'),
        ),
    ]
