# Generated by Django 5.1.4 on 2026-01-04 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0034_config_unloved_exempt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='sessionEnd',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='sessionStart',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='config',
            name='unloved_exempt_status',
            field=models.ManyToManyField(blank=True, help_text='Set of Statuses which should be filtered out of the list of potentially unloved puzzles', related_name='exempt_status', to='puzzles.status'),
        ),
        migrations.AlterField(
            model_name='config',
            name='unloved_exempt_tags',
            field=models.ManyToManyField(blank=True, help_text='Feature to ignore tags not implemented', related_name='exempt_tags', to='puzzles.tag'),
        ),
    ]
