# Generated by Django 6.0 on 2026-01-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0035_accesslog_sessionend_accesslog_sessionstart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='motp',
            field=models.TextField(blank=True, help_text='Message of the puzzle - displayed at top of puzzle page'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='lastUpdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
