# Generated by Django 6.0 on 2026-01-10 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0036_add_puzzle_motp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
